[
{"No": "73471127", "Title": "Curve shape text and its coordinate issue - GCP python", "Content": "\r\n                I am facing issue with google cloud vision api response. there is no issue with proper text image. the problem is with curved shape text written image. i attached for reference.\nwhen i try to detect ...\r\n            ", "Vote": "1", "Answer": "0", "View": "5", "Author": "Gops"},
{"No": "73471116", "Title": "Pytest parametrize + Fixtures", "Content": "\r\n                I am using fixtures to mock my requests.\nI am also using @pytest.mark.parametrize() to add arguments to my tests.\nI can do this:\ndef test_format(mock_api):\n\nI can do this:\n@pytest.mark.parametrize(\n   ...\r\n            ", "Vote": "0", "Answer": "0", "View": "5", "Author": "Nadhem Maaloul"},
{"No": "73471109", "Title": "<__main__.Fruit object at 0x7f38b3344f70> [duplicate]", "Content": "\r\n                Why am I still getting the above message.\nThis is my code, when I execute it displays the above message. iFthe problem with init, I changed it with str, and repr. Still not works\nclass Fruit:\n    def ...\r\n            ", "Vote": "0", "Answer": "0", "View": "9", "Author": "developer"},
{"No": "73471105", "Title": "Python Pandas: Convert dd/mm/yy to dd/mm/yyyy correctly", "Content": "\r\n                I am facing issues when converting a date from dd/mm/yy to dd/mm/yyyy with pandas.\nI have tried this:\ndf['Date'] = pd.to_datetime(df['Date'])\n\nBut somehow for some values the day and month are ...\r\n            ", "Vote": "0", "Answer": "0", "View": "8", "Author": "NickH"},
{"No": "73471104", "Title": "Can you create your own RSS feed that reads from a text file?", "Content": "\r\n                I am trying to create an RSS feed and I would like to be able to put my own content into it. Unfortunately I can only find tutorials on creating a feed with content coming from a website. Is there a ...\r\n            ", "Vote": "0", "Answer": "0", "View": "2", "Author": "antonsmoke"},
{"No": "73471095", "Title": "How can I get y_true class labels?", "Content": "\r\n                I am working on object detection. I have ground truth bounding boxes coordinates and predicted bounding boxes' coordinates. I calculated iou scores for all boxes. So I have those and I would like to ...\r\n            ", "Vote": "0", "Answer": "0", "View": "8", "Author": "atuatu"},
{"No": "73471094", "Title": "sqlalchemy ORM query with foreign key field of a table", "Content": "\r\n                let's say i have these two Tables in Fastapi:\nclass Order:\n    id = Column(Integer, primary_key=True, index=True, )\n\n    owner_id = Column(Integer, nullable=False)\n\n    status = Column(Enum(...\r\n            ", "Vote": "0", "Answer": "0", "View": "5", "Author": "atabak hooshangi"},
{"No": "73471088", "Title": "vscode disable variable view in debugging (python)", "Content": "\r\n                Can I somehow disable the variable view in the debugging mode in vscode?\nMany of my objects are complex and large, and calling the repr() function for each variable takes a lot of time. As I do not ...\r\n            ", "Vote": "0", "Answer": "0", "View": "6", "Author": "DsCpp"},
{"No": "73471071", "Title": "Pandas astye() does not respect given column", "Content": "\r\n                I have an empty dataframe with just the index as the columns are added during later steps.\nimport numpy as np\nimport pandas as pd\nfrom matplotlib import pyplot as plt\r\nstart = int(100E6)\nstop = int(...\r\n            ", "Vote": "0", "Answer": "0", "View": "5", "Author": "clme"},
{"No": "73471033", "Title": "How to extract dependency relations (depency grammer) between POS tags?", "Content": "\r\n                Currently i am working on a project and need some basic idea to solve it.\nI am thinking of implementing a dependency relation extractor by myself so it can show that there is or there is not a ...\r\n            ", "Vote": "1", "Answer": "0", "View": "6", "Author": "Hamid Roghani"},
{"No": "73470988", "Title": "How to assign the records of an array to a JSON parameter?", "Content": "\r\n                I have the following array in Python:\n[\n {'type': 'A1'},\n {\n   'filter': {\n      'type': 'A2',\n      'data': [{'key': 'name_1', 'value': 'a'}, {'key': 'name_2', 'value': 'a'}]\n   }\n },\n {\n   'filter': ...\r\n            ", "Vote": "0", "Answer": "0", "View": "21", "Author": "Fluxy"},
{"No": "73470973", "Title": "How to take specific values from one dataframe and put in another pandas", "Content": "\r\n                There are two dataframes(df and dfi) and I'm trying to locate  those user_id s which are same in both dataframes and want to create new column in df named new_country in which  I will save the ...\r\n            ", "Vote": "0", "Answer": "0", "View": "16", "Author": "Bhawani Rabisankar Sahoo"},
{"No": "73470937", "Title": "Python: TCP connection to 100s of devices", "Content": "\r\n                I have a 3 different systems in action.\nSystem Overview Diagram\n\nI have a server running on cloud which communicate via MQTT protocol to Application.\nThere is Device which connects to Application via ...\r\n            ", "Vote": "-1", "Answer": "0", "View": "13", "Author": "cadmus"},
{"No": "73470933", "Title": "getting \"'NoneType' object has no attribute 'send\" in loop", "Content": "\r\n                Im pretty sure that Im calling loop after bot ready. Reddit part works just fine. I dont get what is causing the error\nreddit = praw.Reddit(client_id = config.client_id,client_secret = config....\r\n            ", "Vote": "0", "Answer": "0", "View": "12", "Author": "MartAyiKoalasi"},
{"No": "73470932", "Title": "how to sum model in Django rest Api", "Content": "\r\n                I am new to Django rest Api devlopment I want to sum rent_amount, bijli_bill, other_amount and get value as Total amount, i dont know to add them pls help\nI want value like this\n\n{\n\"id\": 1,\n&...\r\n            ", "Vote": "0", "Answer": "0", "View": "8", "Author": "Punit Kumar"},
{"No": "73470898", "Title": "Ajax call to python data", "Content": "\r\n                I'm trying to scrape several websites with using requests package / API calls. Now I'm trying to scrape this website : https://sport.circus.be/en/sport/sports-bets/844/227875758 but this is using AJAX ...\r\n            ", "Vote": "0", "Answer": "0", "View": "10", "Author": "Stef Renneboog"},
{"No": "73470895", "Title": "Which python platform is best for redirecting the backend code to a website? [closed]", "Content": "\r\n                I am going to code in python . this code has to redirect to a website and do Machine leering algorithm. i.e., auto fill of form . so which platform is best ?\r\n            ", "Vote": "-2", "Answer": "0", "View": "15", "Author": "Anu Priya"},
{"No": "73470879", "Title": "sparql result dump: JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "Content": "\r\n                trying to wrap a working query into the python code to avoid the time-out issue, but get the error JSONDecodeError: Expecting value: line 1 column 1 (char 0)\ncould someone check what's wrong in there? ...\r\n            ", "Vote": "0", "Answer": "0", "View": "11", "Author": "Elart"},
{"No": "73470873", "Title": "i have accidentally uninstalled all packages in python", "Content": "\r\n                I have accidentally deleted all my Python packages with this command:\npip uninstall -r requirements.txt\n\nIs there an easy way to reinstall all of them?\r\n            ", "Vote": "-5", "Answer": "0", "View": "26", "Author": "jojo_hal"},
{"No": "73470850", "Title": "TypeError: __init__() got an unexpected keyword argument 'categorical_features' ML", "Content": "\r\n                i have this code because i'm trying to transform a \"0\" in a \"0 0 0\", like\n#0 -> 000\n#1 -> 010\n#2 -> 001\nonehotencoder = OneHotEncoder(categorical_features = [0,1,3,5,8,9,...\r\n            ", "Vote": "-1", "Answer": "1", "View": "18", "Author": "gab119"},
{"No": "73470829", "Title": "There is no function named Download() in pytube module", "Content": "\r\n                I Was Trying To Make A Youtube Video And Audio Downloader but when I Call The download() function It Says mp4_video = YouTube(get_link).streams.get_highest_resolution.download()\nAttributeError: '...\r\n            ", "Vote": "0", "Answer": "0", "View": "8", "Author": "Ammar Ehab"},
{"No": "73470799", "Title": "Geocoding: ValueError: Columns must be same length as key", "Content": "\r\n                def my_geocoder(row):\ntry:\npoint = geolocator.geocode(row).point\nreturn pd.DataFrame({'Latitude': point.latitude, 'Longitude': point.longitude})\nexcept:\nreturn None\nNoVA_Properties[['Latitude', '...\r\n            ", "Vote": "-1", "Answer": "0", "View": "9", "Author": "Abas Kasa"},
{"No": "73470791", "Title": "comment puis je r\u00e9cup\u00e9rer les informations rentr\u00e9 dans un modal discord.py 2.0 [closed]", "Content": "\r\n                Comme l'indique la question, j'aimerais r\u00e9cuperer des informations rentr\u00e9s dans un modal, et \u00e9galement v\u00e9rifier que l'utilisateur ne fait pas cancel avant de poursuivre le code. Actuellement j'ai \u00e7a :\n...\r\n            ", "Vote": "-4", "Answer": "0", "View": "18", "Author": "Maxistyle"},
{"No": "73470777", "Title": "Using Google Speadsheet API", "Content": "\r\n                I am trying to use Google Spreadsheet API to automate our reporting process (which is being handled manually). I have created Service Account and downloaded a json file.\n\nimport google.auth\nfrom ...\r\n            ", "Vote": "0", "Answer": "0", "View": "10", "Author": "Viet Nguyen"},
{"No": "73470762", "Title": "Django can't add new item to another database on admin site", "Content": "\r\n                I'm using two databases to create an app and everything looks fine, I can change, delete the existing item but can't add new item to other database table on the admin site. The data should be stored ...\r\n            ", "Vote": "0", "Answer": "0", "View": "13", "Author": "David L"},
{"No": "73470761", "Title": "Looking to add a function that will terminate the program by typing 'exit'", "Content": "\r\n                Right now I have working code that successfully asks the user if they would like to continue on with the program after each input. What I would like to do, however, is instead to allow the user to ...\r\n            ", "Vote": "0", "Answer": "1", "View": "31", "Author": "Garrett"},
{"No": "73470758", "Title": "how to use allow origin regex pattern in jupyter lab config", "Content": "\r\n                Hi I am trying to configure jupyter lab to only allow access from certain IPs. I know that I can set\nc.ServerApp.allow_origin = '*' in the config file at ~/.jupyter/jupyter_lab_config.py but I worry ...\r\n            ", "Vote": "0", "Answer": "1", "View": "6", "Author": "v.tralala"},
{"No": "73470727", "Title": "Syntax error with colon after the if statement [closed]", "Content": "\r\n                [I am in day 3 of python and designing a love calculator. The code below shows a weird syntax error on the colon on the first if statement. where could the problem be?\nI can't seem to find solutions ...\r\n            ", "Vote": "-6", "Answer": "0", "View": "20", "Author": "Wiz98234"},
{"No": "73470722", "Title": "How to read the image through opencv and send it to zxing for detection instead of using the image path?", "Content": "\r\n                How to read the image through opencv and send it to zxing for detection instead of using the image path?\nreader = zxing.BarCodeReader()\nqrcode = reader.decode(img_path)\n\nI want to use the code as ...\r\n            ", "Vote": "0", "Answer": "1", "View": "15", "Author": "SunWenkui"},
{"No": "73470721", "Title": "join dataframes by iterating through dictionary", "Content": "\r\n                import os\nimport glob\nfrom pyspark.sql import functions as F\n \nresult = get_csv_files(\"/test\")\nd= {} \ni = 1\n# loop over the list of csv files\nfor k,v in result.items():\n    df =   spark.read....\r\n            ", "Vote": "1", "Answer": "1", "View": "16", "Author": "Poola Tony"},
{"No": "73470705", "Title": "I'm working on some project in which I should make a connection between an attacker and a victim on pycharm and got some issue with my code", "Content": "\r\n                i'm doing it by 'socket', and the connection was successfully made but my goal is to let the attacker(server) search for files of the victim's and so I planed doing it by 'os.walk' and for that I need ...\r\n            ", "Vote": "-4", "Answer": "0", "View": "12", "Author": "\u05e0\u05d8\u05e2 \u05e9\u05e4\u05e8"},
{"No": "73470692", "Title": "Blocking issue with pandas_datareader in Anaconda - \"conda install -c anaconda pandas-datareader\" not fixing it", "Content": "\r\n                I have a blocking issue with pandas_datareader (Windows) installed with Anaconda/Jupyter. The solutions proposed in other StackOverflow posts are not working as following described.\nThis is a simple ...\r\n            ", "Vote": "0", "Answer": "1", "View": "10", "Author": "fede72bari"},
{"No": "73470687", "Title": "Integers not tuple [closed]", "Content": "\r\n                I want to delete certain elements from my 2d array. I try to achieve that using the following code:\n    trackx=[[x[i],(z[i]-1)*2] for i in range(steps)]## Track projection on X\n    trackx=np.delete(...\r\n            ", "Vote": "-2", "Answer": "0", "View": "23", "Author": "George Demeteiou"},
{"No": "73470683", "Title": "yolov7 Object Detector", "Content": "\r\n                I used yolov5 for my object detection. Now I am trying to improve it to YoloV7. I trained my dataset and convert it from .pt to .onnx. But I cannot implement it to my code. I shared the code in the ...\r\n            ", "Vote": "0", "Answer": "0", "View": "12", "Author": "techgtec"},
{"No": "73470645", "Title": "Why connection is failed [closed]", "Content": "\r\n                I try to make auto post app for Wordpress. And when i run this programm i get this error:\nHTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /wordpress/wp-json/wp/v2/posts ...\r\n            ", "Vote": "-1", "Answer": "0", "View": "12", "Author": "anonimus"},
{"No": "73470641", "Title": "Pandas, .value_counts", "Content": "\r\n                As I was trying to pass two lines that is of theoretically identical results, somehow those produced different outcomes. I have been doing rage checking over the line, the definition of the functions ...\r\n            ", "Vote": "0", "Answer": "0", "View": "21", "Author": "Steven Gee"},
{"No": "73470640", "Title": "how to check/trace why a python script delays to exit", "Content": "\r\n                I have a python script that does some network stuff with the requests library. My issue is that for some reason the python script doesn't seem to exit immediately after it finishes.\nI have measured ...\r\n            ", "Vote": "0", "Answer": "0", "View": "9", "Author": "Kassadin"},
{"No": "73470623", "Title": "Python 3.x Convert nested list of elements into nested dictionary with max recursion", "Content": "\r\n                I would like to convert a nested list like this:\n[\"Pie\", [\"Sugar\", \"Biscuit\", [\"Egg\"] ], \"Cocoa\", []]\n\nto a nested dictionary like this:\n{ \"Pie&...\r\n            ", "Vote": "1", "Answer": "2", "View": "29", "Author": "Dec04"},
{"No": "73470544", "Title": "How to assign to a variable an infinite value in gekko?", "Content": "\r\n                I am trying to assign an infinite value to a variable of gekko in order to help the solver to find a solution. I have tried with the numpy's infinite value and python's own infinite but it is still ...\r\n            ", "Vote": "0", "Answer": "0", "View": "13", "Author": "firaitz"},
{"No": "73470539", "Title": "Why does calling next() on an iterable object not work if I assign the generator function outside of __init__?", "Content": "\r\n                When trying to write a class that acts as an Iterator I came across a problem. To take a deeper look into this I wrote two classes that implement __next__() (I am aware that __iter__() is needed to ...\r\n            ", "Vote": "0", "Answer": "0", "View": "19", "Author": "calvin"},
{"No": "73470534", "Title": "Looping over all XY plots in Abaqus Viewer", "Content": "\r\n                I have a script that does several cosmetic operations on XY plot in Abaqus Viewer. The problem is that the script takes the name of a particular plot and can't be used for all arbitrarily named plots ...\r\n            ", "Vote": "0", "Answer": "0", "View": "10", "Author": "FEA-eng"},
{"No": "73470532", "Title": "how to sequence the dataset into custom amount of data", "Content": "\r\n                Hi I was just working on a dataset about crypto currency and i want to calculate slope based on different range of data in different time range\nfrom scipy.stats import linregress\nslope, intercept, ...\r\n            ", "Vote": "0", "Answer": "0", "View": "10", "Author": "shayanTH78"},
{"No": "73470530", "Title": "How do i print BOTH username and hostname to the console in python? [closed]", "Content": "\r\n                I'm new to python.\nI want to print something like this:\nusername/hostname\nHelp appreciated.\r\n            ", "Vote": "-3", "Answer": "1", "View": "19", "Author": "GrandMarineLCS"},
{"No": "73470503", "Title": "Opencv imencode result different from reading directly from bytes", "Content": "\r\n                I'm currently using OpenCV's imencode to get a binary array into an image it can use. However, I've found that reading the bytes directly is different from opencv's imencode feature. I know this is ...\r\n            ", "Vote": "-1", "Answer": "0", "View": "11", "Author": "ZWang"},
{"No": "73470495", "Title": "remove extra words from text", "Content": "\r\n                ive been trying to remove extra words like {'by','the','and','of' ,'a'}\nfrom text so my best way to do it is like this .\n\nCode :\ndef clean_text(text):\n    \"\"\"\n    takes the text and ...\r\n            ", "Vote": "2", "Answer": "2", "View": "31", "Author": "ImThePeak"},
{"No": "73470494", "Title": "How to trace lost data in grpc?", "Content": "\r\n                I have codes of grpc with a server(c++) and a client(python).\nBut sometimes I find some pieces of data sent by server will be lost when client recieve while others are ok.\nWhat may be the reason?\nAnd ...\r\n            ", "Vote": "0", "Answer": "0", "View": "10", "Author": "f1msch"},
{"No": "73470487", "Title": "How do I store file names in a database in python?", "Content": "\r\n                I am trying to get a list of files in a user specified directory to be saved to a database. What I have at the moment is :\nimport os\nimport sqlite3\n\ndef get_list():\n    folder = input(\"Directory ...\r\n            ", "Vote": "0", "Answer": "1", "View": "19", "Author": "Isaac "},
{"No": "73470447", "Title": "Write value to column if row string contain column name", "Content": "\r\n                I have a dataframe which contains many pre-defined column names. One column of this dataframe contains the name of these columns.\nI want to write the value 1 where the string name is equal to the ...\r\n            ", "Vote": "2", "Answer": "2", "View": "35", "Author": "Shem"},
{"No": "73470422", "Title": "Keras data augmentation layers in model or out of model", "Content": "\r\n                So this may be a silly question but how exactly do the preprocessing layers in keras work, especially in the context of as a part of the model itself. This being compared to preprocessing being ...\r\n            ", "Vote": "0", "Answer": "1", "View": "15", "Author": "Joshua Arenson"},
{"No": "73470409", "Title": "Jupyter Save Hook not working after reinstalling python+pyenv", "Content": "\r\n                I use a jupyter save hook to convert my notebooks into different formats which is defined in /Users/corrie/.jupyter/jupyter_notebook_config.py. This was all working fine until I recently reinstalled ...\r\n            ", "Vote": "0", "Answer": "0", "View": "4", "Author": "Corrie"}
]